import React, { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';

export type Language = 'vi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation data
const translations: Record<Language, Record<string, string>> = {
  vi: {
    // Header
    'header.customerService': 'Chăm sóc khách hàng',
    'header.sellWithUs': 'Bán hàng cùng AudioShop',
    'header.experienceRoom': 'Trải nghiệm phòng âm thanh',
    'header.support': 'Hỗ trợ',
    'header.hello': 'Xin chào',
    'header.logout': 'Đăng xuất',
    'header.login': 'Đăng nhập',
    'header.register': 'Đăng ký',
    'header.account': 'Tài khoản',
    'header.searchPlaceholder': 'Tìm kiếm tai nghe, loa, micro...',
    'header.commitment': 'Cam kết:',
    'header.authentic': '100% hàng thật',
    'header.fastShipping': 'Vận chuyển nhanh chóng',
    'header.refund': 'Hoàn 200% nếu hàng giả',
    'header.return': '7 ngày đổi trả',
    'header.cheapPrice': 'Giá siêu rẻ',
    'header.loadingCategories': 'Đang tải danh mục...',
    // Footer
    'footer.description': 'Chuyên cung cấp thiết bị âm thanh chất lượng cao với giá tốt nhất thị trường.',
    'footer.customerSupport': 'Hỗ Trợ Khách Hàng',
    'footer.helpCenter': 'Trung Tâm Trợ Giúp',
    'footer.shoppingGuide': 'Hướng Dẫn Mua Hàng',
    'footer.returnPolicy': 'Chính Sách Đổi Trả',
    'footer.warrantyPolicy': 'Chính Sách Bảo Hành',
    'footer.payment': 'Thanh Toán',
    'footer.aboutUs': 'Về AudioShop',
    'footer.introduction': 'Giới Thiệu',
    'footer.careers': 'Tuyển Dụng',
    'footer.terms': 'Điều Khoản',
    'footer.privacyPolicy': 'Chính Sách Bảo Mật',
    'footer.authentic': 'Chính Hãng',
    'footer.contact': 'Liên Hệ',
    'footer.address': '123 Đường ABC, Quận 1, TP.HCM',
    'footer.copyright': '© 2025 AudioShop. Tất cả quyền được bảo lưu.',
    // Login
    'login.title': 'Đăng nhập',
    'login.welcome': 'Chào mừng bạn quay trở lại!',
    'login.email': 'Email',
    'login.phone': 'Số điện thoại',
    'login.emailPlaceholder': 'Nhập email của bạn',
    'login.phonePlaceholder': 'Nhập số điện thoại',
    'login.password': 'Mật khẩu',
    'login.passwordPlaceholder': 'Nhập mật khẩu',
    'login.rememberMe': 'Ghi nhớ đăng nhập',
    'login.forgotPassword': 'Quên mật khẩu?',
    'login.loggingIn': 'Đang đăng nhập...',
    'login.loginButton': 'Đăng nhập',
    'login.or': 'Hoặc',
    'login.noAccount': 'Chưa có tài khoản?',
    'login.registerNow': 'Đăng ký ngay',
    'login.errors.emailRequired': 'Vui lòng nhập email!',
    'login.errors.passwordRequired': 'Vui lòng nhập mật khẩu!',
    'login.errors.phoneNotSupported': 'Đăng nhập bằng số điện thoại chưa được hỗ trợ!',
    'login.errors.missingInfo': 'Thiếu thông tin',
    'login.errors.featureNotAvailable': 'Chức năng chưa có',
    'login.errors.loginError': 'Lỗi đăng nhập',
    // Register
    'register.title': 'Đăng ký',
    'register.subtitle': 'Tạo tài khoản để bắt đầu mua sắm!',
    'register.fullName': 'Họ và tên *',
    'register.fullNamePlaceholder': 'Nhập họ và tên của bạn',
    'register.email': 'Email *',
    'register.emailPlaceholder': 'Nhập email của bạn',
    'register.phone': 'Số điện thoại *',
    'register.phonePlaceholder': 'Nhập số điện thoại',
    'register.password': 'Mật khẩu *',
    'register.passwordPlaceholder': 'Nhập mật khẩu (ít nhất 6 ký tự)',
    'register.confirmPassword': 'Xác nhận mật khẩu *',
    'register.confirmPasswordPlaceholder': 'Nhập lại mật khẩu',
    'register.agreeTerms': 'Tôi đồng ý với',
    'register.termsOfService': 'Điều khoản dịch vụ',
    'register.and': 'và',
    'register.privacyPolicy': 'Chính sách bảo mật',
    'register.ofAudioShop': 'của AudioShop *',
    'register.registering': 'Đang đăng ký...',
    'register.registerButton': 'Đăng ký',
    'register.orRegisterWith': 'Hoặc đăng ký với',
    'register.registerWithGoogle': 'Đăng ký với Google',
    'register.hasAccount': 'Đã có tài khoản?',
    'register.loginNow': 'Đăng nhập ngay',
    'register.errors.passwordMismatch': 'Mật khẩu xác nhận không khớp!',
    'register.errors.termsRequired': 'Bạn phải đồng ý với điều khoản dịch vụ để tiếp tục!',
    'register.errors.invalidInfo': 'Thông tin không hợp lệ',
    'register.errors.validationError': 'Lỗi xác thực',
    'register.errors.missingInfo': 'Thiếu thông tin',
    'register.errors.registerError': 'Lỗi đăng ký',
    'register.success.title': 'Đăng ký thành công!',
    'register.success.message': 'Bạn sẽ được chuyển đến trang đăng nhập',
    'register.success.redirectMessage': 'Đăng ký thành công! Vui lòng đăng nhập để tiếp tục.',
    // Product Detail
    'productDetail.productNotFound': 'Không tìm thấy sản phẩm',
    'productDetail.loadError': 'Không thể tải thông tin sản phẩm. Vui lòng thử lại sau.',
    'productDetail.back': 'Quay lại',
    'productDetail.specs.category': 'Danh mục',
    'productDetail.specs.brand': 'Thương hiệu',
    'productDetail.specs.model': 'Model',
    'productDetail.specs.material': 'Chất liệu',
    'productDetail.specs.dimensions': 'Kích thước',
    'productDetail.specs.weight': 'Trọng lượng',
    'productDetail.specs.sku': 'SKU',
    'productDetail.specs.frequencyResponse': 'Dải tần số',
    'productDetail.specs.sensitivity': 'Độ nhạy',
    'productDetail.specs.impedance': 'Trở kháng',
    'productDetail.specs.connectionType': 'Kết nối',
    'productDetail.specs.warrantyPeriod': 'Bảo hành',
    'productDetail.specs.placementType': 'Vị trí đặt',
    'productDetail.specs.title': 'Thông số kỹ thuật',
    'productDetail.description.title': 'Mô tả sản phẩm',
    'productDetail.description.updating': 'Đang cập nhật mô tả...',
    'productDetail.reviews.title': 'Đánh giá',
    'productDetail.voucherLoadError': 'Không thể tải voucher sản phẩm:',
    // Shopping Cart
    'cart.title': 'Giỏ hàng',
    'cart.breadcrumb.cart': 'Giỏ hàng',
    'cart.breadcrumb.checkout': 'Thanh toán',
    'cart.breadcrumb.confirm': 'Xác nhận',
    'cart.loading': 'Đang tải giỏ hàng...',
    'cart.errors.productNotFound': 'Không tìm thấy sản phẩm trong giỏ hàng.',
    'cart.errors.cannotUpdateQuantity': 'Không thể cập nhật số lượng. Vui lòng thử lại.',
    'cart.errors.cannotRemoveItem': 'Không thể xóa sản phẩm. Vui lòng thử lại.',
    'cart.errors.cannotDeleteCart': 'Không thể xóa giỏ hàng. Vui lòng thử lại.',
    'cart.errors.noItemsSelected': 'Vui lòng chọn ít nhất một sản phẩm để mua.',
    'cart.errors.cannotPrepareCheckout': 'Không thể chuẩn bị dữ liệu thanh toán. Vui lòng thử lại.',
    'cart.success.itemRemoved': 'Đã xóa sản phẩm khỏi giỏ hàng',
    'cart.success.cartCleared': 'Đã xóa toàn bộ giỏ hàng',
    'cart.voucher.removedMinOrder': 'Voucher {code} đã được gỡ vì đơn hàng của cửa hàng không đạt tối thiểu {amount}đ.',
    'cart.voucher.alreadyUsed': 'Voucher {code} đã được sử dụng cho {productName}. Mỗi voucher chỉ có thể áp dụng cho một sản phẩm.',
    'cart.voucher.title': 'Voucher',
    'cart.campaign.exceeded': 'Sản phẩm "{productName}" đã vượt quá giới hạn sử dụng chiến dịch. Giá đã được cập nhật về giá gốc.',
    'cart.store.unknown': 'Cửa hàng chưa xác định',
    'cart.product.other': 'sản phẩm khác',
    'cart.errors.title': 'Lỗi',
    'cart.success.title': 'Thành công',
    'cart.warning.title': 'Cảnh báo',
    // Checkout
    'checkout.breadcrumb.cart': 'Giỏ hàng',
    'checkout.breadcrumb.checkout': 'Thanh toán',
    'checkout.breadcrumb.confirm': 'Xác nhận',
    'checkout.loading': 'Đang tải dữ liệu thanh toán...',
    'checkout.sections.deliveryAddress': 'Địa chỉ nhận hàng',
    'checkout.sections.products': 'Sản phẩm',
    'checkout.sections.paymentMethod': 'Phương thức thanh toán',
    'checkout.sections.order': 'Đơn hàng',
    'checkout.submitting': 'Đang gửi đơn hàng...',
    'checkout.confirmButton': 'Xác nhận & Thanh toán',
    'checkout.payment.cod': 'Thanh toán khi nhận hàng (COD)',
    'checkout.errors.cartNotFound': 'Không tìm thấy thông tin giỏ hàng. Vui lòng chọn sản phẩm trước khi thanh toán.',
    'checkout.errors.invalidCart': 'Thông tin giỏ hàng không hợp lệ. Vui lòng chọn lại sản phẩm.',
    'checkout.errors.emptyCart': 'Giỏ hàng của bạn đang trống. Vui lòng chọn sản phẩm trước khi thanh toán.',
    'checkout.errors.selectedItemsNotFound': 'Không tìm thấy sản phẩm đã chọn. Vui lòng kiểm tra lại giỏ hàng.',
    'checkout.errors.cannotLoadData': 'Không thể tải dữ liệu thanh toán. Vui lòng thử lại.',
    'checkout.errors.cannotRemoveItem': 'Không thể xóa sản phẩm. Vui lòng thử lại.',
    'checkout.errors.emptyCartRedirect': 'Giỏ hàng rỗng, quay lại để chọn sản phẩm.',
    'checkout.errors.noAddress': 'Vui lòng chọn địa chỉ nhận hàng.',
    'checkout.errors.noPaymentMethod': 'Vui lòng chọn phương thức thanh toán.',
    'checkout.errors.shippingFeeError': 'Không thể tính phí vận chuyển. Vui lòng kiểm tra lại địa chỉ hoặc thử lại sau.',
    'checkout.errors.invalidPaymentMethod': 'Phương thức thanh toán không hợp lệ.',
    'checkout.errors.checkoutFailed': 'Đã xảy ra lỗi khi đặt hàng. Vui lòng thử lại.',
    'checkout.errors.cannotCreatePayOS': 'Không thể tạo liên kết thanh toán PayOS. Vui lòng thử lại.',
    'checkout.success.orderPlaced': 'Đặt hàng thành công!',
    'checkout.success.itemRemoved': 'Đã xóa sản phẩm khỏi đơn hàng',
    'checkout.orderDescription': 'Đơn hàng từ AudioShop - {count} sản phẩm',
    'checkout.voucher.invalid': 'Voucher {code} không còn hợp lệ.',
    'checkout.voucher.removedMinOrder': 'Voucher {code} đã được gỡ vì đơn hàng không đạt tối thiểu {amount}đ.',
    'checkout.store.unknown': 'Cửa hàng chưa xác định',
    'checkout.notification.title': 'Thông báo',
    'checkout.success.title': 'Thành công',
    'checkout.errors.title': 'Lỗi',
    'checkout.payment.selectTitle': 'Chọn hình thức thanh toán',
    'checkout.payment.notSelected': '---chưa chọn phương thức thanh toán---',
    'checkout.payment.payos': 'PayOS',
    'checkout.summary.title': 'Tóm tắt đơn hàng',
    'checkout.summary.subtotal': 'Tạm tính',
    'checkout.summary.platformDiscount': 'Giảm giá nền tảng',
    'checkout.summary.voucher': 'Voucher',
    'checkout.summary.shippingFee': 'Phí vận chuyển',
    'checkout.summary.total': 'Tổng cộng',
    'checkout.summary.voucherApplied': 'Đã áp dụng voucher: {codes}',
    'checkout.summary.voucherHint': 'Bạn có mã giảm giá? Hãy nhập trước khi thanh toán.',
    // Address Form
    'address.title': 'Địa chỉ nhận hàng',
    'address.description': 'Chọn địa chỉ nhận hàng hoặc thêm địa chỉ mới để giao hàng nhanh chóng hơn.',
    'address.addNew': 'Thêm địa chỉ mới',
    'address.default': 'Mặc định',
    'address.change': 'Thay đổi',
    'address.close': 'Đóng',
    'address.empty': 'Chưa có địa chỉ nào. Vui lòng thêm địa chỉ mới.',
    'address.editTitle': 'Chỉnh sửa địa chỉ',
    'address.add': 'Thêm địa chỉ mới',
    'address.fullName': 'Họ và tên *',
    'address.phone': 'Số điện thoại *',
    'address.label.home': 'Nhà riêng',
    'address.label.work': 'Cơ quan',
    'address.label.other': 'Khác',
    'address.province.select': 'Chọn Tỉnh/Thành *',
    'address.province.loading': 'Đang tải tỉnh/thành...',
    'address.district.select': 'Chọn Quận/Huyện *',
    'address.district.loading': 'Đang tải quận/huyện...',
    'address.ward.select': 'Chọn Phường/Xã *',
    'address.ward.loading': 'Đang tải phường/xã...',
    'address.street': 'Đường',
    'address.addressLine': 'Số nhà / Địa chỉ chi tiết *',
    'address.note': 'Ghi chú',
    'address.setDefault': 'Đặt làm mặc định',
    'address.save': 'Lưu địa chỉ',
    'address.cancel': 'Hủy',
    'address.errors.incomplete': 'Vui lòng điền đầy đủ thông tin địa chỉ',
    'address.errors.cannotSave': 'Không thể lưu địa chỉ',
    'address.errors.cannotDelete': 'Không thể xóa địa chỉ',
    'address.errors.cannotSetDefault': 'Không thể đặt mặc định',
    'address.success.added': 'Thêm địa chỉ thành công',
    'address.success.updated': 'Cập nhật địa chỉ thành công',
    'address.success.deleted': 'Xóa địa chỉ thành công',
    'address.success.setDefault': 'Đã đặt làm địa chỉ mặc định',
    'address.confirmDelete': 'Bạn có chắc chắn muốn xóa địa chỉ "{name}"?',
    // Cart Item List
    'cartItemList.empty': 'Giỏ hàng trống.',
    'cartItemList.loadingAddresses': 'Đang tải địa chỉ...',
    'cartItemList.selectedProducts': 'Đã chọn {selected}/{total} sản phẩm',
    // Store Voucher Picker
    'voucherPicker.discount': 'Giảm',
    'voucherPicker.storeVoucher': 'Voucher cửa hàng',
    'voucherPicker.usedBy': 'Đã được sử dụng bởi {productName}',
    'voucherPicker.minOrder': 'Đơn tối thiểu {amount}đ',
    'voucherPicker.remove': 'Gỡ',
    'voucherPicker.applying': 'Đang áp dụng',
    'voucherPicker.alreadyUsed': 'Voucher {code} đã được sử dụng cho {productName}. Mỗi voucher chỉ có thể áp dụng cho một sản phẩm.',
    'voucherPicker.storeMinOrder': 'Đơn hàng của cửa hàng {storeName} chưa đạt tối thiểu {amount}đ',
    'voucherPicker.percentDiscount': 'Giảm {percent}%',
    'voucherPicker.maxDiscount': 'tối đa {amount}đ',
    'voucherPicker.fixedDiscount': 'Giảm {amount}đ',
    // Summary Box
    'summaryBox.subtotal': 'Tạm tính',
    'summaryBox.platformDiscount': 'Giảm giá nền tảng',
    'summaryBox.voucher': 'Voucher',
    'summaryBox.total': 'Tổng cộng',
    'summaryBox.selectedProducts': '(Đã chọn {count} sản phẩm)',
    'summaryBox.appliedVouchers': 'Đã áp dụng voucher: {codes}',
    'summaryBox.processing': 'Đang xử lý...',
    'summaryBox.buyNow': 'Mua hàng',
    // Select All Bar
    'selectAll.selectAll': 'Chọn tất cả ({count} sản phẩm)',
    'selectAll.deleteAll': 'Xoá tất cả',
    'selectAll.confirmTitle': 'Xoá toàn bộ giỏ hàng?',
    'selectAll.confirmMessage': 'Bạn có chắc chắn muốn xoá tất cả sản phẩm khỏi giỏ hàng? Hành động này không thể hoàn tác.',
    'selectAll.cancel': 'Huỷ',
    'selectAll.confirm': 'Đồng ý xoá',
    // Cart Item Row
    'cartItemRow.variant': 'Phân loại',
    'cartItemRow.default': 'Mặc định',
    'cartItemRow.campaignRemaining': 'Bạn còn {count} lần sử dụng khuyến mãi cho sản phẩm này',
    // Voucher Section
    'voucherSection.title': 'Mã giảm giá',
    'voucherSection.placeholder': 'Nhập mã voucher',
    'voucherSection.apply': 'Áp dụng',
    'voucherSection.discount': 'Giảm',
    'voucherSection.applied': 'Đã áp dụng',
    'voucherSection.remove': 'Gỡ',
    'voucherSection.errors.enterCode': 'Vui lòng nhập mã voucher',
    'voucherSection.errors.invalidCode': 'Mã voucher không hợp lệ hoặc không tồn tại',
    'voucherSection.errors.cannotUse': 'Voucher không thể sử dụng',
    'voucherSection.errors.storeUnknown': 'Không xác định được cửa hàng',
    'voucherSection.errors.minOrder': 'Đơn hàng tối thiểu {min}đ. Hiện tại: {current}đ',
    'voucherSection.appliedMessage': 'Đã áp dụng: {code} - Giảm {amount}đ',
    // Address Selector Compact
    'addressSelector.title': 'Địa chỉ nhận hàng',
    'addressSelector.addNew': 'Thêm địa chỉ mới',
    'addressSelector.change': 'Đổi',
    'addressSelector.empty': 'Chưa có địa chỉ. Vui lòng thêm địa chỉ mới.',
    'addressSelector.success.delete': 'Xóa địa chỉ thành công!',
    'addressSelector.errors.cannotDelete': 'Không thể xóa địa chỉ. Vui lòng thử lại.',
    'addressSelector.confirmDelete': 'Bạn có chắc chắn muốn xóa địa chỉ "{name}"?',
    // Address Form For Cart
    'addressFormCart.editTitle': 'Chỉnh sửa địa chỉ',
    'addressFormCart.addTitle': 'Thêm địa chỉ mới',
    'addressFormCart.cancel': 'Hủy',
    'addressFormCart.fullName': 'Họ tên *',
    'addressFormCart.phone': 'Số điện thoại *',
    'addressFormCart.label.home': 'Nhà riêng',
    'addressFormCart.label.work': 'Cơ quan',
    'addressFormCart.label.other': 'Khác',
    'addressFormCart.province.select': 'Chọn tỉnh/thành phố *',
    'addressFormCart.province.loading': 'Đang tải tỉnh/thành...',
    'addressFormCart.district.select': 'Chọn quận/huyện *',
    'addressFormCart.district.selectFirst': 'Chọn tỉnh trước',
    'addressFormCart.district.loading': 'Đang tải quận/huyện...',
    'addressFormCart.ward.select': 'Chọn phường/xã *',
    'addressFormCart.ward.selectFirst': 'Chọn quận/huyện trước',
    'addressFormCart.ward.loading': 'Đang tải phường/xã...',
    'addressFormCart.street': 'Đường *',
    'addressFormCart.addressLine': 'Số nhà/Địa chỉ chi tiết *',
    'addressFormCart.postalCode': 'Mã bưu điện',
    'addressFormCart.note': 'Ghi chú',
    'addressFormCart.setDefault': 'Đặt làm địa chỉ mặc định',
    'addressFormCart.saving': 'Đang lưu...',
    'addressFormCart.update': 'Cập nhật địa chỉ',
    'addressFormCart.save': 'Lưu địa chỉ',
    'addressFormCart.errors.incomplete': 'Vui lòng điền đầy đủ thông tin địa chỉ',
    'addressFormCart.errors.missingCodes': 'Thiếu mã địa lý: vui lòng chọn Tỉnh/Quận/Phường hợp lệ',
    'addressFormCart.success.update': 'Cập nhật địa chỉ thành công!',
    'addressFormCart.success.add': 'Thêm địa chỉ thành công!',
    'addressFormCart.errors.cannotUpdate': 'Không thể cập nhật địa chỉ. Vui lòng thử lại.',
    'addressFormCart.errors.cannotAdd': 'Không thể thêm địa chỉ. Vui lòng thử lại.',
    // Store Wide Voucher Section
    'storeWideVoucher.title': 'Voucher toàn shop',
    'storeWideVoucher.titleWithStore': 'Voucher toàn shop: {storeName}',
    'storeWideVoucher.collapse': 'Thu gọn',
    'storeWideVoucher.viewVouchers': 'Xem {count} voucher',
    'storeWideVoucher.applied': 'Đã áp dụng',
    'storeWideVoucher.appliedWithCode': 'Đã áp dụng: {code}',
    'storeWideVoucher.discount': 'Giảm',
    'storeWideVoucher.selected': 'Đã chọn',
    'storeWideVoucher.storeWideVoucher': 'Voucher toàn shop',
    'storeWideVoucher.errors.notStarted': 'Voucher chưa đến thời gian áp dụng',
    'storeWideVoucher.errors.expired': 'Voucher đã hết hạn',
    'storeWideVoucher.errors.minOrder': 'Đơn hàng tối thiểu {min}đ. Hiện tại: {current}đ',
  },
  en: {
    // Header
    'header.customerService': 'Customer Service',
    'header.sellWithUs': 'Sell with AudioShop',
    'header.experienceRoom': 'Experience Audio Room',
    'header.support': 'Support',
    'header.hello': 'Hello',
    'header.logout': 'Logout',
    'header.login': 'Login',
    'header.register': 'Register',
    'header.account': 'Account',
    'header.searchPlaceholder': 'Search headphones, speakers, microphones...',
    'header.commitment': 'Commitment:',
    'header.authentic': '100% Authentic',
    'header.fastShipping': 'Fast Shipping',
    'header.refund': '200% Refund if Fake',
    'header.return': '7 Days Return',
    'header.cheapPrice': 'Super Cheap Price',
    'header.loadingCategories': 'Loading categories...',
    // Footer
    'footer.description': 'Specializing in providing high-quality audio equipment at the best market prices.',
    'footer.customerSupport': 'Customer Support',
    'footer.helpCenter': 'Help Center',
    'footer.shoppingGuide': 'Shopping Guide',
    'footer.returnPolicy': 'Return Policy',
    'footer.warrantyPolicy': 'Warranty Policy',
    'footer.payment': 'Payment',
    'footer.aboutUs': 'About AudioShop',
    'footer.introduction': 'Introduction',
    'footer.careers': 'Careers',
    'footer.terms': 'Terms',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.authentic': 'Authentic',
    'footer.contact': 'Contact',
    'footer.address': '123 ABC Street, District 1, Ho Chi Minh City',
    'footer.copyright': '© 2025 AudioShop. All rights reserved.',
    // Login
    'login.title': 'Login',
    'login.welcome': 'Welcome back!',
    'login.email': 'Email',
    'login.phone': 'Phone Number',
    'login.emailPlaceholder': 'Enter your email',
    'login.phonePlaceholder': 'Enter your phone number',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.rememberMe': 'Remember me',
    'login.forgotPassword': 'Forgot password?',
    'login.loggingIn': 'Logging in...',
    'login.loginButton': 'Login',
    'login.or': 'Or',
    'login.noAccount': "Don't have an account?",
    'login.registerNow': 'Register now',
    'login.errors.emailRequired': 'Please enter your email!',
    'login.errors.passwordRequired': 'Please enter your password!',
    'login.errors.phoneNotSupported': 'Phone login is not supported yet!',
    'login.errors.missingInfo': 'Missing Information',
    'login.errors.featureNotAvailable': 'Feature Not Available',
    'login.errors.loginError': 'Login Error',
    // Register
    'register.title': 'Register',
    'register.subtitle': 'Create an account to start shopping!',
    'register.fullName': 'Full Name *',
    'register.fullNamePlaceholder': 'Enter your full name',
    'register.email': 'Email *',
    'register.emailPlaceholder': 'Enter your email',
    'register.phone': 'Phone Number *',
    'register.phonePlaceholder': 'Enter your phone number',
    'register.password': 'Password *',
    'register.passwordPlaceholder': 'Enter password (at least 6 characters)',
    'register.confirmPassword': 'Confirm Password *',
    'register.confirmPasswordPlaceholder': 'Re-enter your password',
    'register.agreeTerms': 'I agree with',
    'register.termsOfService': 'Terms of Service',
    'register.and': 'and',
    'register.privacyPolicy': 'Privacy Policy',
    'register.ofAudioShop': 'of AudioShop *',
    'register.registering': 'Registering...',
    'register.registerButton': 'Register',
    'register.orRegisterWith': 'Or register with',
    'register.registerWithGoogle': 'Register with Google',
    'register.hasAccount': 'Already have an account?',
    'register.loginNow': 'Login now',
    'register.errors.passwordMismatch': 'Passwords do not match!',
    'register.errors.termsRequired': 'You must agree to the terms of service to continue!',
    'register.errors.invalidInfo': 'Invalid Information',
    'register.errors.validationError': 'Validation Error',
    'register.errors.missingInfo': 'Missing Information',
    'register.errors.registerError': 'Registration Error',
    'register.success.title': 'Registration Successful!',
    'register.success.message': 'You will be redirected to the login page',
    'register.success.redirectMessage': 'Registration successful! Please login to continue.',
    // Product Detail
    'productDetail.productNotFound': 'Product not found',
    'productDetail.loadError': 'Unable to load product information. Please try again later.',
    'productDetail.back': 'Go back',
    'productDetail.specs.category': 'Category',
    'productDetail.specs.brand': 'Brand',
    'productDetail.specs.model': 'Model',
    'productDetail.specs.material': 'Material',
    'productDetail.specs.dimensions': 'Dimensions',
    'productDetail.specs.weight': 'Weight',
    'productDetail.specs.sku': 'SKU',
    'productDetail.specs.frequencyResponse': 'Frequency Response',
    'productDetail.specs.sensitivity': 'Sensitivity',
    'productDetail.specs.impedance': 'Impedance',
    'productDetail.specs.connectionType': 'Connection',
    'productDetail.specs.warrantyPeriod': 'Warranty',
    'productDetail.specs.placementType': 'Placement',
    'productDetail.specs.title': 'Specifications',
    'productDetail.description.title': 'Product Description',
    'productDetail.description.updating': 'Updating description...',
    'productDetail.reviews.title': 'Reviews',
    'productDetail.voucherLoadError': 'Unable to load product vouchers:',
    // Shopping Cart
    'cart.title': 'Shopping Cart',
    'cart.breadcrumb.cart': 'Cart',
    'cart.breadcrumb.checkout': 'Checkout',
    'cart.breadcrumb.confirm': 'Confirm',
    'cart.loading': 'Loading cart...',
    'cart.errors.productNotFound': 'Product not found in cart.',
    'cart.errors.cannotUpdateQuantity': 'Unable to update quantity. Please try again.',
    'cart.errors.cannotRemoveItem': 'Unable to remove product. Please try again.',
    'cart.errors.cannotDeleteCart': 'Unable to delete cart. Please try again.',
    'cart.errors.noItemsSelected': 'Please select at least one product to purchase.',
    'cart.errors.cannotPrepareCheckout': 'Unable to prepare checkout data. Please try again.',
    'cart.success.itemRemoved': 'Product removed from cart',
    'cart.success.cartCleared': 'Cart cleared',
    'cart.voucher.removedMinOrder': 'Voucher {code} has been removed because the store order does not meet the minimum {amount}đ.',
    'cart.voucher.alreadyUsed': 'Voucher {code} has already been used for {productName}. Each voucher can only be applied to one product.',
    'cart.voucher.title': 'Voucher',
    'cart.campaign.exceeded': 'Product "{productName}" has exceeded the campaign usage limit. Price has been updated to original price.',
    'cart.store.unknown': 'Unknown Store',
    'cart.product.other': 'other product',
    'cart.errors.title': 'Error',
    'cart.success.title': 'Success',
    'cart.warning.title': 'Warning',
    // Checkout
    'checkout.breadcrumb.cart': 'Cart',
    'checkout.breadcrumb.checkout': 'Checkout',
    'checkout.breadcrumb.confirm': 'Confirm',
    'checkout.loading': 'Loading checkout data...',
    'checkout.sections.deliveryAddress': 'Delivery Address',
    'checkout.sections.products': 'Products',
    'checkout.sections.paymentMethod': 'Payment Method',
    'checkout.sections.order': 'Order',
    'checkout.submitting': 'Submitting order...',
    'checkout.confirmButton': 'Confirm & Pay',
    'checkout.payment.cod': 'Cash on Delivery (COD)',
    'checkout.errors.cartNotFound': 'Cart information not found. Please select products before checkout.',
    'checkout.errors.invalidCart': 'Invalid cart information. Please select products again.',
    'checkout.errors.emptyCart': 'Your cart is empty. Please select products before checkout.',
    'checkout.errors.selectedItemsNotFound': 'Selected products not found. Please check your cart again.',
    'checkout.errors.cannotLoadData': 'Unable to load checkout data. Please try again.',
    'checkout.errors.cannotRemoveItem': 'Unable to remove product. Please try again.',
    'checkout.errors.emptyCartRedirect': 'Cart is empty, go back to select products.',
    'checkout.errors.noAddress': 'Please select a delivery address.',
    'checkout.errors.noPaymentMethod': 'Please select a payment method.',
    'checkout.errors.shippingFeeError': 'Unable to calculate shipping fee. Please check your address or try again later.',
    'checkout.errors.invalidPaymentMethod': 'Invalid payment method.',
    'checkout.errors.checkoutFailed': 'An error occurred while placing order. Please try again.',
    'checkout.errors.cannotCreatePayOS': 'Unable to create PayOS payment link. Please try again.',
    'checkout.success.orderPlaced': 'Order placed successfully!',
    'checkout.success.itemRemoved': 'Product removed from order',
    'checkout.orderDescription': 'Order from AudioShop - {count} products',
    'checkout.voucher.invalid': 'Voucher {code} is no longer valid.',
    'checkout.voucher.removedMinOrder': 'Voucher {code} has been removed because the order does not meet the minimum {amount}đ.',
    'checkout.store.unknown': 'Unknown Store',
    'checkout.notification.title': 'Notification',
    'checkout.success.title': 'Success',
    'checkout.errors.title': 'Error',
    'checkout.payment.selectTitle': 'Select Payment Method',
    'checkout.payment.notSelected': '---payment method not selected---',
    'checkout.payment.payos': 'PayOS',
    'checkout.summary.title': 'Order Summary',
    'checkout.summary.subtotal': 'Subtotal',
    'checkout.summary.platformDiscount': 'Platform Discount',
    'checkout.summary.voucher': 'Voucher',
    'checkout.summary.shippingFee': 'Shipping Fee',
    'checkout.summary.total': 'Total',
    'checkout.summary.voucherApplied': 'Applied vouchers: {codes}',
    'checkout.summary.voucherHint': 'Have a discount code? Enter it before checkout.',
    // Address Form
    'address.title': 'Delivery Address',
    'address.description': 'Select a delivery address or add a new address for faster delivery.',
    'address.addNew': 'Add New Address',
    'address.default': 'Default',
    'address.change': 'Change',
    'address.close': 'Close',
    'address.empty': 'No addresses yet. Please add a new address.',
    'address.editTitle': 'Edit Address',
    'address.add': 'Add New Address',
    'address.fullName': 'Full Name *',
    'address.phone': 'Phone Number *',
    'address.label.home': 'Home',
    'address.label.work': 'Work',
    'address.label.other': 'Other',
    'address.province.select': 'Select Province/City *',
    'address.province.loading': 'Loading provinces...',
    'address.district.select': 'Select District *',
    'address.district.loading': 'Loading districts...',
    'address.ward.select': 'Select Ward *',
    'address.ward.loading': 'Loading wards...',
    'address.district.selectFirst': 'Select province first',
    'address.ward.selectFirst': 'Select district first',
    'address.street': 'Street',
    'address.addressLine': 'House Number / Detailed Address *',
    'address.postalCode': 'Postal Code',
    'address.note': 'Note',
    'address.setDefault': 'Set as Default',
    'address.save': 'Save Address',
    'address.saving': 'Saving...',
    'address.saveChanges': 'Save Changes',
    'address.addAddress': 'Add Address',
    'address.cancel': 'Cancel',
    'address.edit': 'Edit',
    'address.delete': 'Delete',
    'address.viewAll': 'View All Addresses',
    'address.errors.incomplete': 'Please fill in all address information',
    'address.errors.cannotSave': 'Unable to save address',
    'address.errors.cannotDelete': 'Unable to delete address',
    'address.errors.cannotSetDefault': 'Unable to set as default',
    'address.success.added': 'Address added successfully',
    'address.success.updated': 'Address updated successfully',
    'address.success.deleted': 'Address deleted successfully',
    'address.success.setDefault': 'Set as default address',
    'address.confirmDelete': 'Are you sure you want to delete address "{name}"?',
    // Cart Item List
    'cartItemList.empty': 'Cart is empty.',
    'cartItemList.loadingAddresses': 'Loading addresses...',
    'cartItemList.selectedProducts': 'Selected {selected}/{total} products',
    // Store Voucher Picker
    'voucherPicker.discount': 'Discount',
    'voucherPicker.storeVoucher': 'Store Voucher',
    'voucherPicker.usedBy': 'Already used by {productName}',
    'voucherPicker.minOrder': 'Minimum order {amount}đ',
    'voucherPicker.remove': 'Remove',
    'voucherPicker.applying': 'Applying',
    'voucherPicker.alreadyUsed': 'Voucher {code} has already been used for {productName}. Each voucher can only be applied to one product.',
    'voucherPicker.storeMinOrder': 'Store {storeName} order does not meet the minimum {amount}đ',
    'voucherPicker.percentDiscount': 'Discount {percent}%',
    'voucherPicker.maxDiscount': 'max {amount}đ',
    'voucherPicker.fixedDiscount': 'Discount {amount}đ',
    // Summary Box
    'summaryBox.subtotal': 'Subtotal',
    'summaryBox.platformDiscount': 'Platform Discount',
    'summaryBox.voucher': 'Voucher',
    'summaryBox.total': 'Total',
    'summaryBox.selectedProducts': '(Selected {count} products)',
    'summaryBox.appliedVouchers': 'Applied vouchers: {codes}',
    'summaryBox.processing': 'Processing...',
    'summaryBox.buyNow': 'Buy Now',
    // Select All Bar
    'selectAll.selectAll': 'Select All ({count} products)',
    'selectAll.deleteAll': 'Delete All',
    'selectAll.confirmTitle': 'Delete All Items?',
    'selectAll.confirmMessage': 'Are you sure you want to delete all items from your cart? This action cannot be undone.',
    'selectAll.cancel': 'Cancel',
    'selectAll.confirm': 'Confirm Delete',
    // Cart Item Row
    'cartItemRow.variant': 'Variant',
    'cartItemRow.default': 'Default',
    'cartItemRow.campaignRemaining': 'You have {count} more uses of this promotion for this product',
    // Voucher Section
    'voucherSection.title': 'Discount Code',
    'voucherSection.placeholder': 'Enter voucher code',
    'voucherSection.apply': 'Apply',
    'voucherSection.discount': 'Discount',
    'voucherSection.applied': 'Applied',
    'voucherSection.remove': 'Remove',
    'voucherSection.errors.enterCode': 'Please enter voucher code',
    'voucherSection.errors.invalidCode': 'Invalid or non-existent voucher code',
    'voucherSection.errors.cannotUse': 'Voucher cannot be used',
    'voucherSection.errors.storeUnknown': 'Store cannot be determined',
    'voucherSection.errors.minOrder': 'Minimum order {min}đ. Current: {current}đ',
    'voucherSection.appliedMessage': 'Applied: {code} - Discount {amount}đ',
    // Address Selector Compact
    'addressSelector.title': 'Delivery Address',
    'addressSelector.addNew': 'Add New Address',
    'addressSelector.change': 'Change',
    'addressSelector.empty': 'No address yet. Please add a new address.',
    'addressSelector.success.delete': 'Address deleted successfully!',
    'addressSelector.errors.cannotDelete': 'Unable to delete address. Please try again.',
    'addressSelector.confirmDelete': 'Are you sure you want to delete address "{name}"?',
    // Address Form For Cart
    'addressFormCart.editTitle': 'Edit Address',
    'addressFormCart.addTitle': 'Add New Address',
    'addressFormCart.cancel': 'Cancel',
    'addressFormCart.fullName': 'Full Name *',
    'addressFormCart.phone': 'Phone Number *',
    'addressFormCart.label.home': 'Home',
    'addressFormCart.label.work': 'Work',
    'addressFormCart.label.other': 'Other',
    'addressFormCart.province.select': 'Select Province/City *',
    'addressFormCart.province.loading': 'Loading provinces...',
    'addressFormCart.district.select': 'Select District *',
    'addressFormCart.district.selectFirst': 'Select province first',
    'addressFormCart.district.loading': 'Loading districts...',
    'addressFormCart.ward.select': 'Select Ward *',
    'addressFormCart.ward.selectFirst': 'Select district first',
    'addressFormCart.ward.loading': 'Loading wards...',
    'addressFormCart.street': 'Street *',
    'addressFormCart.addressLine': 'House Number/Detailed Address *',
    'addressFormCart.postalCode': 'Postal Code',
    'addressFormCart.note': 'Note',
    'addressFormCart.setDefault': 'Set as Default Address',
    'addressFormCart.saving': 'Saving...',
    'addressFormCart.update': 'Update Address',
    'addressFormCart.save': 'Save Address',
    'addressFormCart.errors.incomplete': 'Please fill in all address information',
    'addressFormCart.errors.missingCodes': 'Missing geographic codes: please select valid Province/District/Ward',
    'addressFormCart.success.update': 'Address updated successfully!',
    'addressFormCart.success.add': 'Address added successfully!',
    'addressFormCart.errors.cannotUpdate': 'Unable to update address. Please try again.',
    'addressFormCart.errors.cannotAdd': 'Unable to add address. Please try again.',
    // Store Wide Voucher Section
    'storeWideVoucher.title': 'Store-wide Voucher',
    'storeWideVoucher.titleWithStore': 'Store-wide Voucher: {storeName}',
    'storeWideVoucher.collapse': 'Collapse',
    'storeWideVoucher.viewVouchers': 'View {count} vouchers',
    'storeWideVoucher.applied': 'Applied',
    'storeWideVoucher.appliedWithCode': 'Applied: {code}',
    'storeWideVoucher.discount': 'Discount',
    'storeWideVoucher.selected': 'Selected',
    'storeWideVoucher.storeWideVoucher': 'Store-wide Voucher',
    'storeWideVoucher.errors.notStarted': 'Voucher has not started yet',
    'storeWideVoucher.errors.expired': 'Voucher has expired',
    'storeWideVoucher.errors.minOrder': 'Minimum order {min}đ. Current: {current}đ',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    // Get language from localStorage or default to 'vi'
    const savedLanguage = localStorage.getItem('app_language') as Language;
    return savedLanguage === 'en' || savedLanguage === 'vi' ? savedLanguage : 'vi';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] || key;
    
    // Replace placeholders if params provided
    if (params) {
      Object.entries(params).forEach(([paramKey, paramValue]) => {
        text = text.replace(new RegExp(`\\{${paramKey}\\}`, 'g'), String(paramValue));
      });
    }
    
    return text;
  };

  useEffect(() => {
    // Save language preference to localStorage
    localStorage.setItem('app_language', language);
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
